### ISSUE TITLE
Must specify userName when calling with non-User credentials

### ISSUE THREAD

**Issue by ArisBee** [Setfive/cloudwatch-autowatch#2]
I've successfully made the script work by hardcoding an IAM `UserName` in `/dist/index.js`, before the `iam.getUser` call. Without this workaround, I cannot run the script, neither with an instance role nor with AWS keys set as env parameters.

I think there is something to fix there, here the link to the corresponding function in AWS javascript SDK:
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/IAM.html#getUser-property

**Comment by adatta02** [comment]
Can you paste in the error you're getting? 

I just tried using the environment variables and it authenticated correctly. It's delegating authentication to the AWS SDK so it should "just work". 

Actually, what AWS region are you in? Just noticed its defaulting "us-east-1" - https://github.com/Setfive/cloudwatch-autowatch/blob/master/src/config.ts#L20 which might be your issue?

**Comment by ArisBee** [comment]
I'm in the "eu-west-1", I don't think the error comes from there though.

Here a pastebin of the error: https://pastebin.com/LQLz7sDU

**Comment by adatta02** [comment]
It's interesting "listSnsTopics" works since that requires authentication as well. 

To confirm, you're setting environment variables for an IAM user that has permissions to create CloudWatch alarms right? Or are you using IAM roles from the EC2?

**Comment by ArisBee** [comment]
I've tried both methods with the FullAdminAccess policy in a dev account.

However, it's normal the error happens only for the  "generateAlarms" command as the "listSnsTopics" doesn't use the methods which generates the error message [here](https://github.com/Setfive/cloudwatch-autowatch/blob/fa9a8aacf71c65187c33ca9c2f268594d9d247d3/dist/index.js#L33)

**Comment by adatta02** [comment]
Ah I see, the "getUser" call seems to fail when using an IAM role. On https://github.com/Setfive/cloudwatch-autowatch/commit/a82f52a0a7c1a33674c4898a027d532bb346df9b switched to use the STS service and it should be working now.

Tested and confirmed on an EC2 with the "arn:aws:iam::aws:policy/AdministratorAccess" role granted.

**Comment by ArisBee** [comment]
I've pulled the update, it seems it fixed the issue.
Case closed.
